### ISSUE TITLE
Setup vendor model and controller(s)

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dataloading-management#2]
In general, FOLIO will be the source of truth for organization data, however, we need to capture some necessary data for local use and display.

Fields that are required in the model:
- folio_id: Source from `ID` field and should conform to UUID pattern
- folio_code: Source from the `code` field
- name: Source from the `name` field
- highlight: true/false (default: false) initially this will be used to display the initial priority vendors on the homepage.

The above fields will be used for interacting in the interface. If any additional details are required for coordination with the data pipeline they will be fetched in realtime using the folio_client.

Note: We will NOT be editing vendor records in this application, so we do not need an edit interface.

Data pattern from FOLIO:

```
{'id': '7842df10-f041-481d-b80f-c403b39aebdd',
   'name': 'San Francisco Symphony',
   'code': 'SFSYMPHONY-SUL',
   'exportToAccounting': True,
   'status': 'Active',
   'organizationTypes': [],
   'aliases': [],
   'addresses': [{'addressLine1': '201 Van Ness Ave.',
     'city': 'San Francisco',
     'stateRegion': 'CA',
     'zipCode': '94102',
     'isPrimary': True,
     'categories': ['06dcca1b-7d28-4dc7-8650-5270bd9f342a',
      'ab760714-4185-4859-b0dd-3e72f01c5c52',
      '5bbcbc77-b435-4031-b211-998e05d9d2f8']}],
   'phoneNumbers': [{'phoneNumber': '415-503-5461',
     'categories': ['06dcca1b-7d28-4dc7-8650-5270bd9f342a',
      'ab760714-4185-4859-b0dd-3e72f01c5c52',
      '5bbcbc77-b435-4031-b211-998e05d9d2f8'],
     'type': 'Office',
     'isPrimary': True}],
   'emails': [{'value': 'Eneveu@sfsymphony.org',
     'isPrimary': True,
     'categories': ['06dcca1b-7d28-4dc7-8650-5270bd9f342a',
      'ab760714-4185-4859-b0dd-3e72f01c5c52',
      '5bbcbc77-b435-4031-b211-998e05d9d2f8']}],
   'urls': [],
   'contacts': [],
   'agreements': [],
   'erpCode': '553022FEEDER',
   'vendorCurrencies': ['USD'],
   'claimingInterval': 364,
   'interfaces': [],
   'accounts': [],
   'isVendor': True,
   'changelogs': [],
   'acqUnitIds': ['bd6c5f05-9ab3-41f7-8361-1c1e847196d3'],
   'metadata': {'createdDate': '2023-02-09T18:30:33.839+00:00',
    'createdByUserId': '3e2ed889-52f2-45ce-8a30-8767266f07d2',
    'updatedDate': '2023-02-09T18:30:33.839+00:00',
    'updatedByUserId': '3e2ed889-52f2-45ce-8a30-8767266f07d2'}}
```

**Comment by ndushay** [comment]
@aaron-collier questions:
- routes for all of these?  `[:index, :new, :create, :show, :destroy]`  Will we want to have `:destroy`?
- should `highlight` be `priority` ?

**Comment by aaron-collier** [comment]
1. We aren't going to have edit/create pages, so if I don't think we need the routes as long as the creation/update/destroy can still happen via code
2. I'm not particular about the naming, so if it makes more sense to you, go with it :-)
