### ISSUE TITLE
Setup standard development dependencies and services

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dataloading-management#5]
- [x] setup and configure circleci
- [ ] setup and configure coverage in codeclimate
- [x] clear up any linting issues
- [ ] add usual badges to the README

**Comment by mjgiarlo** [comment]
AFAICT, codeclimate integration is now working (I clicked some buttons in the CodeClimate UI for the DLM project). See here: https://github.com/sul-dlss/dataloading-management/pull/27

And the badges look good, though maybe we want the OpenAPI badge. Any other badges?
